// Copyright AB. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Vital_Health)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Vital_MaxHealth)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Vital_Shield)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Vital_MaxShield)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Vital_IncomingDamage)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Dexterity)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Instinct)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Intelligence)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Resilience)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Speed)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Primary_Strength)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Ammo_Weapon1MagazineFill)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Ammo_Weapon1MagazineCapacity)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Ammo_Weapon1AmmoReserve)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Ammo_Weapon1MaxAmmo)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Ammo_Weapon2MagazineFill)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Ammo_Weapon2MagazineCapacity)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Ammo_Weapon2AmmoReserve)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Ammo_Weapon2MaxAmmo)
