// Copyright AB. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Npc)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Npc_Ally_A)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Npc_Ally_B)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Npc_Ally_C)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Npc_Ally_D)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Npc_Ally_E)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Npc_Ally_F)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Npc_Ally_G)
