// Copyright AB. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

// Events
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_ActivateEquipment_SocketSwitch)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Death_DetachItems)

// Montages
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Gestures)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Gestures_Nod)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Gestures_PointHigh)

// Scripts
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyBIntro1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyDIntro1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyAIntro1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyBIntro2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyDIntro2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyAIntro2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyAIntro3)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyDIntro3)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_PlayerInWaterTowerAlley)

// Targets
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Target_Tutorial_WaterTower)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Target_Tutorial_WaterTowerAlleyGate)
