// Copyright AB. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_ActivateEquipment_SocketSwitch)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Tutorial_HowToLook)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Tutorial_HowToMove)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_Bark_AllyAIntro1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_Bark_AllyAIntro2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_Bark_AllyAIntro3)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_Bark_AllyAIntro4)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_Bark_AllyBIntro1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_Bark_AllyBIntro2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_Bark_AllyBIntro3)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_Bark_AllyDIntro1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_Bark_AllyDIntro2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_Bark_AllyDIntro3)

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_LookTarget_WaterTower)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_LookTarget_WaterTowerAlleyGate)
