// Copyright AB. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

// Blackboard
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_BlackboardKey)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_BlackboardKey_CombatTargetActor)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_BlackboardKey_FollowActor)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_BlackboardKey_LookTargetLocation)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_BlackboardKey_MoveTargetLocation)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_BlackboardKey_PatrolTargetActor)

// Events
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_ActivateEquipment_SocketSwitch)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_Death_DetachItems)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Event_SpecialMove_Execute)

// Input Mapping Contexts
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_InputMappingContext_DisableSquadMemberSwitching)

// Montages
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Gestures)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Gestures_Nod)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Montage_Gestures_PointHigh)

// Paths
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Path_A)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Path_B)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Path_C)

// Scripts
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyBIntro1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyDIntro1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyAIntro1)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyBIntro2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyDIntro2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyAIntro2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyAIntro3)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_AllyDIntro3)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Script_Tutorial_PlayerInWaterTowerAlley)

// Targets
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Target_Tutorial_WaterTower)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Target_Tutorial_WaterTowerAlleyGate)
